#!/bin/bash
# (c) 2004 Florian Sippel <flo@noris.de>
# ---------------------------------------
# Edited: 2016 by Jean-Denis Gebhardt <jean-denis.gebhardt@noris.de>
# Version: 1.1
# ---------------------------------------

RET="$(/usr/bin/clamdscan --quiet --stdout - <<< 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' 2>&1)"

case $? in
  0) echo "Critical: Eicar Virus not found!" && EXIT=2 ;;
  1) echo "OK: Eicar Virus found!" && EXIT=0 ;;
  2) echo -e "Warning: An error occured executing clamdscan!\n${RET}" && EXIT=1 ;;
  *) echo -e "Unknown: Could not execute clamdscan!\n${RET}" && EXIT=3 ;;
esac

exit ${EXIT}
